# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc6xgYpdMXVlUtsWF6_bAlpFA_R2daOX
"""

# Colab-ready: MIS completo con output numerico e grafici (inclusi grafici a barre)
# Copia e incolla l'intera cella in Colab ed esegui.
# Produce: tabelle numeriche stampate, istogrammi, scatter, bar charts, salvataggio file .npz e .png.

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
sns.set(style="whitegrid")

# ---------------------------
# Parametri (modificare se serve)
# ---------------------------
d = 20                    # lunghezza sequenza
Kmax = 45                 # q_i in 1..45
alpha = 5.0               # parametro phi (regola selezione attorno a 45)
thetas = [1.5, 2.5, 4.0]  # tilt parameters da combinare
N_each = 40000            # campioni per tilt (totale = N_each * len(thetas))
bootstrap_B = 300         # bootstrap resamples per CI
rng_seed = 123456
save_figures = True
save_prefix = "mis_complete"    # prefisso file salvati

# ---------------------------
# Utility functions
# ---------------------------
rng = np.random.default_rng(rng_seed)
k = np.arange(1, Kmax+1)

def logsumexp(a):
    m = np.max(a)
    return m + np.log(np.sum(np.exp(a - m)))

def log_phi(sum_q, mean_q, alpha):
    # log ⟨Φ|seq⟩ normalizzato rispetto a w_max
    return -alpha * (mean_q - 45.0)**2 + 90.0 - (sum_q / 10.0)

# base distribution p1 (log)
log_p1 = -k / 10.0
log_p1 -= logsumexp(log_p1)
p1 = np.exp(log_p1)

# ---------------------------
# Campionamento MIS: per-theta e concatenazione
# ---------------------------
start_time = time.time()
per_theta_stats = []
all_vals = []
all_meanq = []
all_sumq = []
all_log_IS = []
all_theta_idx = []

for ti, theta in enumerate(thetas):
    # costruisci p_tilt (log)
    log_p_tilt = (theta - 1/10.0) * k
    log_p_tilt -= logsumexp(log_p_tilt)
    p_tilt = np.exp(log_p_tilt)

    # campiona sequenze
    seqs = rng.choice(k, size=(N_each, d), p=p_tilt)
    sum_q = seqs.sum(axis=1)
    mean_q = sum_q / d

    # log ⟨Φ⟩ e valore grezzo
    log_val = log_phi(sum_q, mean_q, alpha)
    val_raw = np.exp(np.clip(log_val, -700, 700))

    # log IS weight: sum_i (log p1[q_i] - log p_tilt[q_i])
    log_IS = np.sum(log_p1[seqs-1] - log_p_tilt[seqs-1], axis=1)

    # diagnostici per-theta (prima della normalizzazione globale)
    # normalizziamo temporaneamente i pesi locali per ESS locale
    lw_shift_local = log_IS - np.max(log_IS)
    w_local = np.exp(lw_shift_local)
    w_local /= w_local.sum()
    ESS_local = 1.0 / np.sum(w_local**2)
    per_theta_stats.append({
        "theta": theta,
        "N": N_each,
        "ESS_local": float(ESS_local),
        "mean_meanq": float(mean_q.mean()),
        "median_meanq": float(np.median(mean_q))
    })

    # accumula
    all_vals.append(val_raw)
    all_meanq.append(mean_q)
    all_sumq.append(sum_q)
    all_log_IS.append(log_IS)
    all_theta_idx.append(np.full(N_each, ti, dtype=int))

# concat
vals = np.concatenate(all_vals)
meanq = np.concatenate(all_meanq)
sumq = np.concatenate(all_sumq)
log_IS_all = np.concatenate(all_log_IS)
theta_idx = np.concatenate(all_theta_idx)
N_total = vals.size
elapsed = time.time() - start_time

# ---------------------------
# Normalizzazione pesi globali (MIS)
# ---------------------------
log_w_shift = log_IS_all - np.max(log_IS_all)
w_unnorm = np.exp(log_w_shift)
w = w_unnorm / w_unnorm.sum()

# Diagnostics globali
ESS = 1.0 / np.sum(w**2)
max_w = float(w.max())
median_w = float(np.median(w))
p99_w = float(np.percentile(w, 99))

# Stima E_orig[⟨Φ⟩] e var pesata
est_mean_phi = float(np.sum(w * vals))
var_hat = float(np.sum(w * (vals - est_mean_phi)**2))
se_approx = float(np.sqrt(var_hat / ESS)) if ESS > 1 else float('nan')

# Stime probabilità coda per soglie
m_values = [44.5, 44.8, 45.0]
tail_probs = {m: float(np.sum(w * (meanq >= m).astype(float))) for m in m_values}

# Bootstrap weighted resample per CI su E_orig[⟨Φ⟩]
indices = np.arange(N_total)
boot_est = np.empty(bootstrap_B)
for b in range(bootstrap_B):
    res_idx = rng.choice(indices, size=N_total, replace=True, p=w)
    boot_est[b] = vals[res_idx].mean()
ci_lower, ci_upper = np.percentile(boot_est, [2.5, 97.5])
boot_mean = float(np.mean(boot_est))

# ---------------------------
# Output numerico stampato (tabella compatta)
# ---------------------------
print("\n=== RISULTATI MIS COMPLETO ===")
print(f"Campionati {N_total} sequenze in {elapsed:.2f}s (thetas={thetas})")
print(f"Alpha (phi): {alpha}")
print("\n-- Statistiche globali MIS --")
print(f"ESS (global): {ESS:.6f}")
print(f"max weight: {max_w:.6e}")
print(f"median weight: {median_w:.6e}")
print(f"99th percentile weight: {p99_w:.6e}")
print(f"E_orig[⟨Φ⟩] (MIS self-normalized): {est_mean_phi:.6e}")
print(f"Weighted variance: {var_hat:.6e}")
print(f"Approx SE (via ESS): {se_approx:.6e}")
print(f"Bootstrap mean: {boot_mean:.6e}, 95% CI: [{ci_lower:.6e}, {ci_upper:.6e}]")
print("\n-- Probabilità di coda (MIS weighted estimates) --")
for m, p in tail_probs.items():
    print(f"P_orig(mean >= {m}): {p:.6e}")

print("\n-- Statistiche per theta (ESS locale e medie) --")
for s in per_theta_stats:
    print(f"theta={s['theta']}: ESS_local={s['ESS_local']:.3f}, mean(mean_q)={s['mean_meanq']:.3f}, median(mean_q)={s['median_meanq']:.3f}")

# ---------------------------
# Grafici (scatter, istogrammi, barre)
# ---------------------------

# 1) Histogram delle medie campionate (per-theta overlay)
plt.figure(figsize=(9,4))
bins = np.linspace(1,45,90)
for ti, theta in enumerate(thetas):
    mask = (theta_idx == ti)
    plt.hist(meanq[mask], bins=bins, alpha=0.5, label=f"theta={theta}", density=False)
plt.axvline(45, color='red', linestyle='--', label='45')
plt.xlabel('media ⟨q⟩_seq')
plt.ylabel('counts')
plt.title('Istogramma delle medie campionate per theta')
plt.legend()
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_hist_meanq_per_theta.png', dpi=200)
plt.show()

# 2) Scatter: ⟨Φ⟩ vs ⟨q⟩ con marker size ~ peso
plt.figure(figsize=(9,5))
sizes = 60 * (w / (w.max() + 1e-300))
plt.scatter(meanq, vals, s=6, alpha=0.12, c=meanq, cmap='viridis', label='raw ⟨Φ⟩')
plt.scatter(meanq, vals, s=sizes, c='orange', alpha=0.35, label='weighted (marker size ~ weight)')
plt.colorbar(label='⟨q⟩_seq')
plt.xlabel('media ⟨q⟩_seq')
plt.ylabel('⟨Φ_α|seq⟩ (raw)')
plt.title('Scatter: ⟨Φ⟩ vs ⟨q⟩ (marker size ~ peso normalizzato)')
plt.xlim(1,45)
plt.ylim(-0.02,1.05)
plt.legend()
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_scatter_weights.png', dpi=200)
plt.show()

# 3) Bar chart: ESS locale per theta
plt.figure(figsize=(7,4))
theta_vals = [s['theta'] for s in per_theta_stats]
ess_vals = [s['ESS_local'] for s in per_theta_stats]
plt.bar([str(t) for t in theta_vals], ess_vals, color='C2')
plt.xlabel('theta')
plt.ylabel('ESS locale')
plt.title('ESS locale per theta')
for i, v in enumerate(ess_vals):
    plt.text(i, v + max(ess_vals)*0.02, f"{v:.1f}", ha='center')
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_bar_ESS_per_theta.png', dpi=200)
plt.show()

# 4) Bar chart: tail probabilities (per soglia) — singolo grafico
plt.figure(figsize=(8,4))
m_labels = [str(m) for m in m_values]
prob_vals = [tail_probs[m] for m in m_values]
plt.bar(m_labels, prob_vals, color='C3')
plt.yscale('log')
plt.xlabel('Soglia media ⟨q⟩')
plt.ylabel('P_orig(mean >= m) (log scale)')
plt.title('Probabilità di coda sotto la misura originale (MIS weighted)')
for i, v in enumerate(prob_vals):
    plt.text(i, v*1.5 if v>0 else 0, f"{v:.2e}", ha='center')
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_bar_tail_probs.png', dpi=200)
plt.show()

# 5) Histogram dei pesi (log10)
plt.figure(figsize=(8,3))
plt.hist(np.log10(w + 1e-300), bins=120, color='C0', alpha=0.9)
plt.xlabel('log10(normalized weight)')
plt.title('Distribuzione log10 dei pesi normalizzati')
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_hist_log10_weights.png', dpi=200)
plt.show()

# 6) Bar chart: top-k pesi (most informative samples)
k_top = 10
top_idx = np.argsort(w)[-k_top:][::-1]
top_weights = w[top_idx]
top_meanq = meanq[top_idx]
plt.figure(figsize=(9,4))
x = np.arange(k_top)
plt.bar(x, top_weights, color='C4')
plt.xticks(x, [f"{i+1}" for i in range(k_top)])
plt.xlabel('Top-k samples (rank)')
plt.ylabel('peso normalizzato')
plt.title('Top-k pesi normalizzati (campioni più influenti)')
for i, (pw, mq) in enumerate(zip(top_weights, top_meanq)):
    plt.text(i, pw*1.05, f"{pw:.2e}\nmean={mq:.2f}", ha='center', fontsize=8)
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_bar_topk_weights.png', dpi=200)
plt.show()

# 7) Binned bar chart: IS-weighted mean ⟨Φ⟩ per bin (barre)
bins_bar = np.linspace(1,45,18)  # 17 bins
bin_idx = np.digitize(meanq, bins_bar)
bin_centers = 0.5*(bins_bar[:-1] + bins_bar[1:])
mean_val_per_bin = []
count_per_bin = []
for i in range(1, len(bins_bar)):
    mask = (bin_idx == i)
    if np.any(mask):
        w_mask = w[mask]
        vals_mask = vals[mask]
        mean_val_per_bin.append(np.sum(w_mask * vals_mask) / (w_mask.sum() if w_mask.sum()>0 else np.nan))
        count_per_bin.append(mask.sum())
    else:
        mean_val_per_bin.append(0.0)
        count_per_bin.append(0)
plt.figure(figsize=(10,4))
plt.bar(bin_centers, mean_val_per_bin, width=(bins_bar[1]-bins_bar[0])*0.9, color='C5', alpha=0.8)
plt.xlabel('media ⟨q⟩_seq (bin centers)')
plt.ylabel('IS-weighted mean of ⟨Φ⟩ in bin')
plt.title('Bar chart: IS-weighted mean ⟨Φ⟩ per bin di ⟨q⟩')
for i, v in enumerate(mean_val_per_bin):
    if v > 0:
        plt.text(bin_centers[i], v + max(mean_val_per_bin)*0.02, f"{v:.2e}", ha='center', fontsize=8)
plt.tight_layout()
if save_figures: plt.savefig(f'{save_prefix}_bar_binned_mean_phi.png', dpi=200)
plt.show()

# ---------------------------
# Salvataggio risultati e dati grezzi
# ---------------------------
np.savez(f'{save_prefix}_results.npz',
         vals=vals, meanq=meanq, sumq=sumq, log_IS_all=log_IS_all,
         w=w, est_mean_phi=est_mean_phi, var_hat=var_hat, se_approx=se_approx,
         ESS=ESS, boot_est=boot_est, per_theta_stats=per_theta_stats,
         tail_probs=tail_probs, thetas=thetas, alpha=alpha, N_each=N_each)

print("\nTutti i risultati e le figure (se save_figures=True) sono stati salvati con prefisso:", save_prefix)
print("File principali: ", f"{save_prefix}_results.npz")
print("Fine esecuzione.")