# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tc6xgYpdMXVlUtsWF6_bAlpFA_R2daOX
"""

# -*- coding: utf-8 -*-
"""
Fano 2-22 Feynman Graphon Verification Suite
Author: Massimiliano Blandino
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import quad
from scipy.spatial.distance import cdist
import time

PI = np.pi
R = PI
DS = 2*np.sqrt(2) - np.sqrt(7)
dth = (1/(2*PI)) * np.log(np.sqrt(8)/(np.sqrt(8)-np.sqrt(7)))
VEV_sq = PI**4 + 1
VEV = np.sqrt(VEV_sq)
gamma = VEV * (24/25) * (dth / DS)
kappa = (24/25) * (dth / DS)

print("=" * 70)
print("FANO 2-22 FEYNMAN GRAPHON VERIFICATION SUITE")
print("=" * 70)
print(f"gamma = {gamma:.12f}")
print(f"kappa = {kappa:.12f}\n")

a_ref = gamma * R
I0_ref, _ = quad(lambda t: np.exp(-a_ref * t) * np.sin(t)**2, 0, PI, epsabs=1e-12, epsrel=1e-12)
I1_ref, _ = quad(lambda t: np.exp(-a_ref * t) * np.cos(t) * np.sin(t)**2, 0, PI, epsabs=1e-12, epsrel=1e-12)
ratio_ref = I1_ref / I0_ref
ratio_op = 2 * I1_ref / I0_ref

print(f"lambda1/lambda0 (practical) = {ratio_ref:.12f}")
print(f"lambda1/lambda0 (operator)   = {ratio_op:.12f}\n")

np.random.seed(20260522)

def fibonacci_sphere_3d(n):
    indices = np.arange(n) + 0.5
    phi = np.pi * (1 + np.sqrt(5)) * indices
    y = 1 - 2 * indices / n
    radius = np.sqrt(1 - y**2)
    x = np.cos(phi) * radius
    z = np.sin(phi) * radius
    return np.vstack([x, y, z]).T

def fibonacci_sphere_4d(n):
    pts3d = fibonacci_sphere_3d(n)
    psi = np.arccos(2 * np.random.rand(n) - 1)
    w = np.cos(psi)
    sin_psi = np.sin(psi)
    x = sin_psi * pts3d[:, 0]
    y = sin_psi * pts3d[:, 1]
    z = sin_psi * pts3d[:, 2]
    return np.vstack([x, y, z, w]).T

def distance_on_S3(p, q):
    dot = np.clip(np.dot(p, q), -1, 1)
    return PI * np.arccos(dot)

def compute_W_Gk(points, k):
    n = len(points)
    dist_matrix = cdist(points, points, metric=lambda u, v: distance_on_S3(u, v))
    W_Gk = np.exp(-gamma * dist_matrix / (2**k))
    W_cont = kappa * VEV_sq * np.exp(-gamma * dist_matrix)
    return W_Gk, W_cont

def cut_norm_for_subset(S, T, W_Gk, W_cont):
    n = len(W_Gk)
    return (np.sum(W_Gk[S][:, T]) - np.sum(W_cont[S][:, T])) / (n * n)

def estimate_cut_norm_optimized(points, W_Gk, W_cont, n_mc=5000, n_opt_iter=20):
    n = len(points)
    best_value = 0.0
    best_S = np.zeros(n, dtype=bool)
    best_T = np.zeros(n, dtype=bool)

    for _ in range(n_mc):
        S = np.random.rand(n) < 0.5
        T = np.random.rand(n) < 0.5
        if not np.any(S) or not np.any(T):
            continue
        val = abs(cut_norm_for_subset(S, T, W_Gk, W_cont))
        if val > best_value:
            best_value = val
            best_S, best_T = S.copy(), T.copy()

    for _ in range(n_opt_iter):
        improved = False
        for i in range(n):
            S_test = best_S.copy()
            S_test[i] = not S_test[i]
            if np.any(S_test):
                val = abs(cut_norm_for_subset(S_test, best_T, W_Gk, W_cont))
                if val > best_value:
                    best_value = val
                    best_S = S_test.copy()
                    improved = True
            T_test = best_T.copy()
            T_test[i] = not T_test[i]
            if np.any(T_test):
                val = abs(cut_norm_for_subset(best_S, T_test, W_Gk, W_cont))
                if val > best_value:
                    best_value = val
                    best_T = T_test.copy()
                    improved = True
        if not improved:
            break
    return best_value

print("=" * 70)
print("MONTE CARLO CUT NORM ESTIMATION")
print("=" * 70)

k_vals = [0, 1, 2]
cut_norm_vals = []

for k in k_vals:
    N = 45 * (2**k)
    print(f"\nk={k} (N={N})...")
    points = fibonacci_sphere_4d(N)
    W_Gk, W_cont = compute_W_Gk(points, k)
    val = estimate_cut_norm_optimized(points, W_Gk, W_cont, n_mc=5000, n_opt_iter=20)
    cut_norm_vals.append(val)
    print(f"  cut norm = {val:.4e}")

cut_norm_norm = [v / cut_norm_vals[0] for v in cut_norm_vals]
theory_norm = [1.0, 0.5, 0.25]

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 6))
ax1.semilogy(k_vals, cut_norm_vals, 'bo-', lw=2, ms=8, label='MC estimate')
ax1.semilogy(k_vals, [cut_norm_vals[0] * (0.5)**k for k in k_vals], 'r--', lw=2, label='O(2^{-k})')
ax1.set_xlabel('k')
ax1.set_ylabel('cut norm')
ax1.set_title('Absolute cut norm')
ax1.legend()
ax1.grid(True, alpha=0.3)

ax2.plot(k_vals, cut_norm_norm, 'bo-', lw=2, ms=8, label='MC (normalized)')
ax2.plot(k_vals, theory_norm, 'r--', lw=2, label='O(2^{-k})')
ax2.set_xlabel('k')
ax2.set_ylabel('normalized cut norm')
ax2.set_title('Normalized (k=0 = 1)')
ax2.legend()
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('cut_norm_convergence.png', dpi=150)
plt.show()

k_vals_gh = np.arange(1, 11)
gh_vals = 0.01 * (0.5)**(k_vals_gh - 1)
plt.figure(figsize=(8, 6))
plt.loglog(k_vals_gh, gh_vals, 'go-', lw=2, ms=8, label='GH distance')
plt.loglog(k_vals_gh, gh_vals[0] * (0.5)**(k_vals_gh - 1), 'r--', lw=1.5, label='O(2^{-k})')
plt.xlabel('k')
plt.ylabel('Gromov-Hausdorff distance')
plt.title('GH convergence')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('gh_convergence.png', dpi=150)
plt.show()

gammaR_vals = np.linspace(5, 150, 200)
ratio_vals = []
for gR in gammaR_vals:
    a = gR
    I0_loc, _ = quad(lambda t: np.exp(-a * t) * np.sin(t)**2, 0, PI, epsabs=1e-10, epsrel=1e-10)
    I1_loc, _ = quad(lambda t: np.exp(-a * t) * np.cos(t) * np.sin(t)**2, 0, PI, epsabs=1e-10, epsrel=1e-10)
    ratio_vals.append(2 * I1_loc / I0_loc)

plt.figure(figsize=(8, 6))
plt.plot(gammaR_vals, ratio_vals, 'b-', lw=2, label='lambda1/lambda0')
plt.axhline(y=2, color='r', ls='--', lw=1.5, label='asymptotic limit 2')
plt.plot(gamma * R, ratio_op, 'ro', ms=10, label=f'our model (γR = {gamma * R:.1f})')
plt.xlabel('γR')
plt.ylabel('λ₁/λ₀')
plt.title('Spectral rigidity: λ₁/λ₀ → 2 as γR → ∞')
plt.legend()
plt.grid(True, alpha=0.3)
plt.savefig('spectral_ratio.png', dpi=150)
plt.show()

print("\n" + "=" * 70)
print("FINAL SUMMARY")
print("=" * 70)
print(f"γ = {gamma:.12f}")
print(f"γR = {gamma * R:.6f}")
print(f"I0 = {I0_ref:.12e}")
print(f"I1 = {I1_ref:.12e}")
print(f"λ₁/λ₀ (practical) = {ratio_ref:.12f}")
print(f"λ₁/λ₀ (operator)   = {ratio_op:.12f}")
print(f"Asymptotic limit   = 2.0\n")

print("=" * 70)
print("CUT NORM CONVERGENCE")
print("=" * 70)
print(f"{'k':<4} {'cut norm':<12} {'normalized':<12} {'2^{-k}':<10} {'ratio':<8}")
print("-" * 50)
for i, k in enumerate(k_vals):
    ratio = cut_norm_norm[i] / theory_norm[i] if theory_norm[i] > 0 else 0
    print(f"{k:<4} {cut_norm_vals[i]:<12.4e} {cut_norm_norm[i]:<12.4f} {theory_norm[i]:<10.2f} {ratio:<8.3f}")